// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: add_staff.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AddStaffData with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddStaffData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddStaffData with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddStaffDataMultiError, or
// nil if none found.
func (m *AddStaffData) ValidateAll() error {
	return m.validate(true)
}

func (m *AddStaffData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetToken() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AddStaffDataValidationError{
						field:  fmt.Sprintf("Token[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AddStaffDataValidationError{
						field:  fmt.Sprintf("Token[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AddStaffDataValidationError{
					field:  fmt.Sprintf("Token[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetNewStaffEmail() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AddStaffDataValidationError{
						field:  fmt.Sprintf("NewStaffEmail[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AddStaffDataValidationError{
						field:  fmt.Sprintf("NewStaffEmail[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AddStaffDataValidationError{
					field:  fmt.Sprintf("NewStaffEmail[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return AddStaffDataMultiError(errors)
	}
	return nil
}

// AddStaffDataMultiError is an error wrapping multiple validation errors
// returned by AddStaffData.ValidateAll() if the designated constraints aren't met.
type AddStaffDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddStaffDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddStaffDataMultiError) AllErrors() []error { return m }

// AddStaffDataValidationError is the validation error returned by
// AddStaffData.Validate if the designated constraints aren't met.
type AddStaffDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddStaffDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddStaffDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddStaffDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddStaffDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddStaffDataValidationError) ErrorName() string { return "AddStaffDataValidationError" }

// Error satisfies the builtin error interface
func (e AddStaffDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddStaffData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddStaffDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddStaffDataValidationError{}
