// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: business_hours.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusinessHours struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: dynamodbav:"start,omitempty"
	Start string `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	// @gotags: dynamodbav:"end,omitempty"
	End string `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *BusinessHours) Reset() {
	*x = BusinessHours{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_hours_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusinessHours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessHours) ProtoMessage() {}

func (x *BusinessHours) ProtoReflect() protoreflect.Message {
	mi := &file_business_hours_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessHours.ProtoReflect.Descriptor instead.
func (*BusinessHours) Descriptor() ([]byte, []int) {
	return file_business_hours_proto_rawDescGZIP(), []int{0}
}

func (x *BusinessHours) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *BusinessHours) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

var File_business_hours_proto protoreflect.FileDescriptor

var file_business_hours_proto_rawDesc = []byte{
	0x0a, 0x14, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x38, 0x0a, 0x0e,
	0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x42, 0x70, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x42, 0x12, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x48, 0x6f, 0x75, 0x72,
	0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x6f, 0x64, 0x61, 0x79, 0x73, 0x74, 0x65, 0x63, 0x68, 0x73,
	0x2f, 0x67, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x55, 0x58, 0x58,
	0xaa, 0x02, 0x04, 0x55, 0x73, 0x65, 0x72, 0xca, 0x02, 0x04, 0x55, 0x73, 0x65, 0x72, 0xe2, 0x02,
	0x10, 0x55, 0x73, 0x65, 0x72, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x04, 0x55, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_business_hours_proto_rawDescOnce sync.Once
	file_business_hours_proto_rawDescData = file_business_hours_proto_rawDesc
)

func file_business_hours_proto_rawDescGZIP() []byte {
	file_business_hours_proto_rawDescOnce.Do(func() {
		file_business_hours_proto_rawDescData = protoimpl.X.CompressGZIP(file_business_hours_proto_rawDescData)
	})
	return file_business_hours_proto_rawDescData
}

var file_business_hours_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_business_hours_proto_goTypes = []interface{}{
	(*BusinessHours)(nil), // 0: user.business_hours
}
var file_business_hours_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_business_hours_proto_init() }
func file_business_hours_proto_init() {
	if File_business_hours_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_business_hours_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusinessHours); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_business_hours_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_business_hours_proto_goTypes,
		DependencyIndexes: file_business_hours_proto_depIdxs,
		MessageInfos:      file_business_hours_proto_msgTypes,
	}.Build()
	File_business_hours_proto = out.File
	file_business_hours_proto_rawDesc = nil
	file_business_hours_proto_goTypes = nil
	file_business_hours_proto_depIdxs = nil
}
