// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: user_service.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UserServicePingData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserServicePingData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserServicePingData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserServicePingDataMultiError, or nil if none found.
func (m *UserServicePingData) ValidateAll() error {
	return m.validate(true)
}

func (m *UserServicePingData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetHi()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserServicePingDataValidationError{
					field:  "Hi",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserServicePingDataValidationError{
					field:  "Hi",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetHi()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserServicePingDataValidationError{
				field:  "Hi",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UserServicePingDataMultiError(errors)
	}
	return nil
}

// UserServicePingDataMultiError is an error wrapping multiple validation
// errors returned by UserServicePingData.ValidateAll() if the designated
// constraints aren't met.
type UserServicePingDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserServicePingDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserServicePingDataMultiError) AllErrors() []error { return m }

// UserServicePingDataValidationError is the validation error returned by
// UserServicePingData.Validate if the designated constraints aren't met.
type UserServicePingDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserServicePingDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserServicePingDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserServicePingDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserServicePingDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserServicePingDataValidationError) ErrorName() string {
	return "UserServicePingDataValidationError"
}

// Error satisfies the builtin error interface
func (e UserServicePingDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserServicePingData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserServicePingDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserServicePingDataValidationError{}

// Validate checks the field values on Ok with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Ok) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Ok with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in OkMultiError, or nil if none found.
func (m *Ok) ValidateAll() error {
	return m.validate(true)
}

func (m *Ok) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSuccess()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OkValidationError{
					field:  "Success",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OkValidationError{
					field:  "Success",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSuccess()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OkValidationError{
				field:  "Success",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetStatusCode()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OkValidationError{
					field:  "StatusCode",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OkValidationError{
					field:  "StatusCode",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStatusCode()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OkValidationError{
				field:  "StatusCode",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return OkMultiError(errors)
	}
	return nil
}

// OkMultiError is an error wrapping multiple validation errors returned by
// Ok.ValidateAll() if the designated constraints aren't met.
type OkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OkMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OkMultiError) AllErrors() []error { return m }

// OkValidationError is the validation error returned by Ok.Validate if the
// designated constraints aren't met.
type OkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OkValidationError) ErrorName() string { return "OkValidationError" }

// Error satisfies the builtin error interface
func (e OkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOk.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OkValidationError{}

// Validate checks the field values on Any with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Any) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Any with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in AnyMultiError, or nil if none found.
func (m *Any) ValidateAll() error {
	return m.validate(true)
}

func (m *Any) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TypeUrl

	// no validation rules for Value

	if len(errors) > 0 {
		return AnyMultiError(errors)
	}
	return nil
}

// AnyMultiError is an error wrapping multiple validation errors returned by
// Any.ValidateAll() if the designated constraints aren't met.
type AnyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AnyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AnyMultiError) AllErrors() []error { return m }

// AnyValidationError is the validation error returned by Any.Validate if the
// designated constraints aren't met.
type AnyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AnyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AnyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AnyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AnyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AnyValidationError) ErrorName() string { return "AnyValidationError" }

// Error satisfies the builtin error interface
func (e AnyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAny.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AnyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AnyValidationError{}
